on: [push]
name: build
jobs:
  runhaskell:
    name: haskell-projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '9.0.1'
          enable-stack: true
          stack-version: 'latest'
      - run: stack build
      - run: stack test
      - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.stack') }}-${{ hashFiles('**/stack.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        stack update
        stack build
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
