on: [push]
name: build
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.0.1' # Exact version of ghc to use
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
